name: 'SHOCK! Culture'
favicon: null
layout_spectrum: 0.46660185093060136
typography_spectrum: 0.7859946480020881
title: 'SHOCK! Culture - Breaking Barriers & Building Bridges'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020224'
    - '#ffffff'
    - '#7b7a8c'
    - '#cba660'
    - '#c9cbcd'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
