name: 'SHOCK! Culture'
favicon: null
layout_spectrum: 0.26874
typography_spectrum: 0.07702
title: 'SHOCK! Culture  - Cultural Modern Wear'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e183a'
    - '#91483d'
    - '#4a4d56'
    - '#bdbd8a'
    - '#be8672'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
